/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var sdl = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,4],$V1=[1,11],$V2=[1,12],$V3=[6,32],$V4=[6,25,29],$V5=[1,29],$V6=[5,18],$V7=[1,53],$V8=[1,51],$V9=[1,63],$Va=[1,62],$Vb=[5,6,8,14,18];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"query_args":3,"query":4,",":5,"NAME":6,"(":7,")":8,"action_query":9,"action_queries":10,"transition":11,"->":12,"transfer":13,">":14,"transfers":15,"effect":16,"[":17,"]":18,"action":19,":":20,"STR":21,"actions":22,"state":23,";":24,"*":25,"states":26,"item":27,"{":28,"}":29,"items":30,"sdl":31,"EOF":32,"$accept":0,"$end":1},
terminals_: {2:"error",5:",",6:"NAME",7:"(",8:")",12:"->",14:">",17:"[",18:"]",20:":",21:"STR",24:";",25:"*",28:"{",29:"}",32:"EOF"},
productions_: [0,[3,1],[3,3],[4,1],[4,4],[9,3],[10,1],[10,3],[11,2],[13,2],[13,3],[15,1],[15,3],[16,1],[16,3],[16,3],[16,6],[16,4],[16,4],[16,7],[19,3],[19,4],[22,1],[22,3],[23,4],[23,5],[23,7],[23,8],[26,1],[26,2],[27,5],[27,7],[30,1],[30,2],[31,2]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1: case 6: case 11: case 22: case 28: case 32:
 this.$ = [$$[$0]]; 
break;
case 2: case 7: case 12: case 23:
 this.$ = [$$[$0-2]].concat($$[$0]); 
break;
case 3:
 this.$ = ["hasName",$$[$0]]; 
break;
case 4:
 this.$ = [$$[$0-3], $$[$0-1]]; 
break;
case 5:
 this.$ = {"subject":$$[$0-2],"verb":$$[$0-1],"object":$$[$0]}; 
break;
case 8:
 this.$ = {"next_state":$$[$0]}; 
break;
case 9:
 this.$ = {"item":$$[$0]}; 
break;
case 10:
 this.$ = {"item":$$[$0],"destination":$$[$0-2]}; 
break;
case 13:
 this.$ = {"transition":$$[$0]}; 
break;
case 14:
 this.$ = {"transfers":$$[$0-1]}; 
break;
case 15:
 this.$ = {"action_queries":$$[$0-1]}; 
break;
case 16:
 this.$ = {"transfers":$$[$0-4], "action_queries":$$[$0-1]}; 
break;
case 17:
 this.$ = {"transition":$$[$0-3],"transfers":$$[$0-1]}; 
break;
case 18:
 this.$ = {"transition":$$[$0-3],"action_queries":$$[$0-1]}; 
break;
case 19:
 this.$ = {"transition":$$[$0-6],"transfers":$$[$0-4],"action_queries":$$[$0-1]}; 
break;
case 20:
 this.$ = {"name":$$[$0-2][0] == "_" ? $$[$0-2].slice(1) : $$[$0-2],"description":$$[$0],"protected":$$[$0-2][0] == "_"}; 
break;
case 21:
 this.$ = {"name":$$[$0-3][0] == "_" ? $$[$0-3].slice(1) : $$[$0-3],"description":$$[$0-1],"protected":$$[$0-3][0] == "_","effect":$$[$0]}; 
break;
case 24:
 this.$ = {"name":$$[$0-3],"description":$$[$0-1],"current":false}; 
break;
case 25:
 this.$ = {"name":$$[$0-3],"description":$$[$0-1],"current":true}; 
break;
case 26:
 this.$ = {"name":$$[$0-6],"description":$$[$0-4],"current":false,"actions":$$[$0-2]}; 
break;
case 27:
 this.$ = {"name":$$[$0-6],"description":$$[$0-4],"current":true,"actions":$$[$0-2]}; 
break;
case 29: case 33:
 this.$ = [$$[$0-1]].concat($$[$0]); 
break;
case 30:
 this.$ = {"name":$$[$0-4],"states":$$[$0-2]}; 
break;
case 31:
 this.$ = {"name":$$[$0-4],"parent":$$[$0-6],"states":$$[$0-2]}; 
break;
case 34:
 return $$[$0-1]; 
break;
}
},
table: [{6:$V0,27:3,30:2,31:1},{1:[3]},{32:[1,5]},{6:$V0,27:3,30:6,32:[2,32]},{14:[1,8],28:[1,7]},{1:[2,34]},{32:[2,33]},{6:$V1,23:10,25:$V2,26:9},{6:[1,13]},{29:[1,14]},{6:$V1,23:10,25:$V2,26:15,29:[2,28]},{20:[1,16]},{6:[1,17]},{28:[1,18]},{24:[1,19]},{29:[2,29]},{21:[1,20]},{20:[1,21]},{6:$V1,23:10,25:$V2,26:22},o($V3,[2,30]),{17:[1,24],24:[1,23]},{21:[1,25]},{29:[1,26]},o($V4,[2,24]),{6:$V5,19:28,22:27},{17:[1,31],24:[1,30]},{24:[1,32]},{18:[1,33]},{5:[1,34],18:[2,22]},{20:[1,35]},o($V4,[2,25]),{6:$V5,19:28,22:36},o($V3,[2,31]),{24:[1,37]},{6:$V5,19:28,22:38},{21:[1,39]},{18:[1,40]},o($V4,[2,26]),{18:[2,23]},o($V6,[2,20],{16:41,11:42,12:[1,44],17:[1,43]}),{24:[1,45]},o($V6,[2,21]),o($V6,[2,13],{17:[1,46]}),{4:52,6:$V7,9:50,10:48,13:49,14:$V8,15:47},{6:[1,54]},o($V4,[2,27]),{4:52,6:$V7,9:50,10:56,13:49,14:$V8,15:55},{18:[1,57]},{18:[1,58]},{5:[1,59],18:[2,11]},{5:[1,60],18:[2,6]},{4:61,6:$V7},{6:$V9,14:$Va},o($Vb,[2,3],{7:[1,64]}),o([5,17,18],[2,8]),{18:[1,65]},{18:[1,66]},o($V6,[2,14],{17:[1,67]}),o($V6,[2,15]),{4:69,6:$V7,13:49,14:$V8,15:68},{4:71,6:$V7,9:50,10:70},o($V6,[2,9]),{4:72,6:$V7},{4:73,6:$V7},{3:74,4:75,6:$V7},o($V6,[2,17],{17:[1,76]}),o($V6,[2,18]),{4:71,6:$V7,9:50,10:77},{18:[2,12]},{14:$Va},{18:[2,7]},{6:$V9},o($V6,[2,10]),o($V6,[2,5]),{8:[1,78]},{5:[1,79],8:[2,1]},{4:71,6:$V7,9:50,10:80},{18:[1,81]},o($Vb,[2,4]),{3:82,4:75,6:$V7},{18:[1,83]},o($V6,[2,16]),{8:[2,2]},o($V6,[2,19])],
defaultActions: {5:[2,34],6:[2,33],15:[2,29],38:[2,23],68:[2,12],70:[2,7],82:[2,2]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:return "NAME"
break;
case 2:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return "STR"
break;
case 3:return "{"
break;
case 4:return "}"
break;
case 5:return ";"
break;
case 6:return "*"
break;
case 7:return ":"
break;
case 8:return ">"
break;
case 9:return "["
break;
case 10:return "]"
break;
case 11:return "->"
break;
case 12:return ","
break;
case 13:return "EOF"
break;
case 14:return "INVALID"
break;
}
},
rules: [/^(?:\s+)/,/^(?:[$a-zA-Z_][a-zA-Z_0-9]*)/,/^(?:'(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")/,/^(?:\{)/,/^(?:\})/,/^(?:;)/,/^(?:\*)/,/^(?::)/,/^(?:>)/,/^(?:\[)/,/^(?:\])/,/^(?:->)/,/^(?:,)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = sdl;
exports.Parser = sdl.Parser;
exports.parse = function () { return sdl.parse.apply(sdl, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}